import Header from '@/components/header'

import '@/styles/globals.css'

const DEFAULT_TITLE = 'app'

export const metadata = {
  manifest: '/manifest.json',
  // <meta name='mobile-web-app-capable' content='yes' />
  // <meta name='apple-mobile-web-app-capable' content='yes' />
  // <meta name='msapplication-starturl' content='/' />
  // <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no' /> // default in nextjs
  // <meta charSet='utf-8' /> // default in nextjs
  description: 'Generated by create-t3-app',
  themeColor: '#193549',
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
    apple: '/icon.png',
  },
  // <link
  //   href='splash.png'
  //   media='(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)'
  //   rel='apple-touch-startup-image'
  // />
  // title: title === DEFAULT_TITLE ? title : `${title} - ${DEFAULT_TITLE}`,
  title: DEFAULT_TITLE,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen flex-col bg-cb-dark-blue text-cb-white'>
          <Header title={DEFAULT_TITLE} />
          {children}
        </div>
      </body>
    </html>
  )
}
